#!/bin/bash	
set -x

VERSION=$1

if git ls-remote --tags https://github.com/snapcore/snapd.git "$VERSION" | grep "$VERSION"; then
    echo "$VERSION"
elif git ls-remote --heads https://github.com/snapcore/snapd.git "release/$VERSION" | grep "$VERSION"; then
    echo "release/$VERSION"
else
    echo "branch not found"
    exit 1
fi