#!/bin/bash

sudo apt update
sudo apt install -y python3-pip
sudo pip3 install jsonpath-ng

git clone https://github.com/sergiocazzolato/snappy-qa-jobs.git
( cd snappy-qa-jobs && ./service-generator -h )