#!/bin/bash

sudo apt update
sudo apt install -y python3-pip
pip3 install jsonpath-ng py-trello

git clone https://github.com/sergiocazzolato/snappy-qa-jobs.git
( cd snappy-qa-jobs && ./service-generator -h )