summary: Update spread for the service agents specified

restore: |
    rm -rf ./spread

execute: |
    # Update spread version
    wget https://storage.googleapis.com/snapd-spread-tests/spread/spread-amd64.tar.gz
    tar -xvzf spread-amd64.tar.gz
    test -x ./spread

    if [ -n "$AGENT_ID" ]; then
        agents="$AGENT_PREFIX-$AGENT_ID"
    else
        agents=$(lxd.lxc list --format csv | cut -d ',' -f1)
    fi

    for agent in $agents; do
        lxd.lxc file push ./spread "$agent"/usr/local/bin/spread
        lxd.lxc exec "$agent" -- chown root.spread /usr/local/bin/spread
        lxd.lxc exec "$agent" -- chmod u=rwx,g=rxs,o=rx /usr/local/bin/spread
    done
